vich_uploader:
    db_driver: orm # ou mongodb ou phpcr, selon votre utilisation
    mappings:
        attachment:
            uri_prefix: '/uploads/attachments'
            upload_destination: '%kernel.project_dir%/public/uploads/attachments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
